{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "cd026f0b",
   "metadata": {},
   "source": [
    "## Debugging and Handling Exceptions\n",
    "\n",
    "There are 3 main types of errors\n",
    "\n",
    "- Syntax Errors - example, parentheses have to come in matching pairs, so (1 + 2) is legal, but 8) is a syntax error.\n",
    "   \n",
    "   Syantax refers to the rules that govern a programming language.\n",
    "- Semantic Errors - Program will run successfully, but it will not do what is expected \n",
    "  \n",
    "  Semantics in programming refers to the meaning of valid syntax.\n",
    "- Runtime Errors - Error does not appear until after the program has started running. This are called **Exceptions** because they indicate that something exceptional (and bad) has happened. Examples of this is memory errors, errors in source code e.g division by zero, missing files errors \n",
    "\n",
    "Most exceptions are not handled by programs and result in error messages \n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9cec840e",
   "metadata": {},
   "source": [
    "ERRORS ENCOUNTERED\n",
    "\n",
    "- SyntaxErrors -  mistakes in the source code, such as spelling and punctuation errors, incorrect labels, and so on, which cause an error message to be generated by the compiler.\n",
    "\n",
    "- NameError - raised when you try to use a variable or a function name that is not valid.\n",
    "\n",
    "- TypeError - raised whenever an operation is performed on an incorrect/unsupported object type. eg mathematical operation on a string\n",
    "\n",
    "- ZeroDivisionError -  is due to a number being divided by zero. Any number divided by zero gives the answer “equal to infinity.” Unfortunately, no data structure in the world of programming can store an infinite amount of data. Hence, if any number is divided by zero, we get the arithmetic exception .\n",
    "\n",
    "- FileNotFoundError - indicates that Python cannot find the file you are referencing. Python raises this error because your program cannot continue running without being able to access the file to which your program refers. \n",
    "\n",
    "- IOError - It is an error raised when an input/output operation fails, such as the print statement or the open() function when trying to open a file that does not exist. Occurs when a program is unable to perform a read or write operation on a file or device.\n",
    "\n",
    "- KeyboardInterrupt -  occurs when a user manually tries to halt the running program by using the Ctrl + C or Ctrl + Z commands or by interrupting the kernel in the case of Jupyter Notebook.\n",
    "\n",
    "- IndentationError- can occur when the spaces or tabs are not placed properly.\n",
    "- ValueError -  raised when a function receives an argument of the correct type but an inappropriate value."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6a771c6a",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "expected ':' (1959479098.py, line 5)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[1], line 5\u001b[1;36m\u001b[0m\n\u001b[1;33m    if a == b\u001b[0m\n\u001b[1;37m             ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m expected ':'\n"
     ]
    }
   ],
   "source": [
    "#Example of a Syntax error\n",
    "a = 5\n",
    "b= 6\n",
    "\n",
    "if a == b"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f23d0d23",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "incomplete input (940944798.py, line 2)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[2], line 2\u001b[1;36m\u001b[0m\n\u001b[1;33m    \u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m incomplete input\n"
     ]
    }
   ],
   "source": [
    "print(\"Hello\"\n",
    "      "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "97fdb18d",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "expected an indented block after 'if' statement on line 4 (2467571711.py, line 5)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[3], line 5\u001b[1;36m\u001b[0m\n\u001b[1;33m    print(\"N is 3\")\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mIndentationError\u001b[0m\u001b[1;31m:\u001b[0m expected an indented block after 'if' statement on line 4\n"
     ]
    }
   ],
   "source": [
    "#Example of an Indentation error\n",
    "n = 3\n",
    "\n",
    "if n > 1: \n",
    "print(\"N is 3\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "010d0ed6",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "expected an indented block after 'for' statement on line 3 (3163733764.py, line 4)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[4], line 4\u001b[1;36m\u001b[0m\n\u001b[1;33m    print(i)\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mIndentationError\u001b[0m\u001b[1;31m:\u001b[0m expected an indented block after 'for' statement on line 3\n"
     ]
    }
   ],
   "source": [
    "list1 = [1,2,3]\n",
    "\n",
    "for i in list1:\n",
    "print(i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "5c41943e",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[5], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# Example of ZeroDivisionError\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[38;5;241m10\u001b[39m\u001b[38;5;241m*\u001b[39m(\u001b[38;5;241;43m1\u001b[39;49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[38;5;241;43m0\u001b[39;49m)\n",
      "\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "# Example of ZeroDivisionError\n",
    "10*(1/0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "8113c9b1",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'spam' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[6], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m#Example of NameError - the word spam is not defined anywhere in the program yet the compiler is trying to access it\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[38;5;241m4\u001b[39m\u001b[38;5;241m+\u001b[39m\u001b[43mspam\u001b[49m\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m3\u001b[39m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'spam' is not defined"
     ]
    }
   ],
   "source": [
    "#Example of NameError - the word spam is not defined anywhere in the program yet the compiler is trying to access it\n",
    "4+spam*3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a27a4069",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'name' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[7], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mname\u001b[49m)\n",
      "\u001b[1;31mNameError\u001b[0m: name 'name' is not defined"
     ]
    }
   ],
   "source": [
    "print(name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "fa097ad6",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'my_function' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[8], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[43mmy_function\u001b[49m()\n",
      "\u001b[1;31mNameError\u001b[0m: name 'my_function' is not defined"
     ]
    }
   ],
   "source": [
    "my_function()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c4e35da5",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "can only concatenate str (not \"int\") to str",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[9], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# TypeError - tyring to perform concatenation of a string and an integer\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m2\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m2\u001b[39;49m\n",
      "\u001b[1;31mTypeError\u001b[0m: can only concatenate str (not \"int\") to str"
     ]
    }
   ],
   "source": [
    "# TypeError - tyring to perform concatenation of a string and an integer\n",
    "'2'+ 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "9fe05638",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "unsupported operand type(s) for /: 'int' and 'str'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[10], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m#Example of TypeError - cannot divide an integer and a string\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[38;5;241;43m4\u001b[39;49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mh\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\n",
      "\u001b[1;31mTypeError\u001b[0m: unsupported operand type(s) for /: 'int' and 'str'"
     ]
    }
   ],
   "source": [
    "#Example of TypeError - cannot divide an integer and a string\n",
    "4/'h'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "7677f8ee",
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: 'file.txt'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[11], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m#Example of FileNotFoundError\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m file \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mopen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mfile.txt\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py:282\u001b[0m, in \u001b[0;36m_modified_open\u001b[1;34m(file, *args, **kwargs)\u001b[0m\n\u001b[0;32m    275\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m file \u001b[38;5;129;01min\u001b[39;00m {\u001b[38;5;241m0\u001b[39m, \u001b[38;5;241m1\u001b[39m, \u001b[38;5;241m2\u001b[39m}:\n\u001b[0;32m    276\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[0;32m    277\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIPython won\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mt let you open fd=\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfile\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m by default \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    278\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mas it is likely to crash IPython. If you know what you are doing, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    279\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124myou can use builtins\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m open.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    280\u001b[0m     )\n\u001b[1;32m--> 282\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m io_open(file, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "\u001b[1;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: 'file.txt'"
     ]
    }
   ],
   "source": [
    "#Example of FileNotFoundError\n",
    "file = open(\"file.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "195b75f0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter your age: ojh\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "invalid literal for int() with base 10: 'ojh'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[12], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m#Example of ValueError - the compiler expects an integer and not a string\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m age \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mint\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;28;43minput\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mEnter your age: \u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m      3\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mYou must be \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m years old\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(age))\n",
      "\u001b[1;31mValueError\u001b[0m: invalid literal for int() with base 10: 'ojh'"
     ]
    }
   ],
   "source": [
    "#Example of ValueError - the compiler expects an integer and not a string\n",
    "age = int(input(\"Enter your age: \"))\n",
    "print(\"You must be {} years old\".format(age))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4be3a63b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "9ae49912",
   "metadata": {},
   "source": [
    "The last line of the error message indicates what happened. Exceptions come in different types, and the type is printed as part of the message: the types in the example are ZeroDivisionError,NameError and TypeError. \n",
    "\n",
    "The string printed as the exception type is the name of the built-in\n",
    "exception that occurred. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a43c6721",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "a8e115d5",
   "metadata": {},
   "source": [
    "## Dealing with exceptions \n",
    "Unlike syntax errors, exceptions are not always fatal. Exceptions can be handled with the use of\n",
    "a try statement. \n",
    "\n",
    "Syntax \n",
    "\n",
    "    try: \n",
    "        statement(s)\n",
    "    except:\n",
    "        exception\n",
    "    \n",
    "The try statement works as follows:\n",
    "    \n",
    "   - First, the **try** clause (the statement(s) between the try and except keywords) is executed.\n",
    "    \n",
    "   - If **no** exception occurs, the except clause is **skipped** and execution of the try statement is finished.\n",
    "\n",
    "   - If an **exception** occurs during execution of the try clause, the rest of the clause is skipped.Then if its type matches the exception named after the except keyword, the **except clause is executed**, and then execution continues after the try statement.\n",
    "\n",
    "   - If an exception occurs which **does not match the exception** named in the except clause, it is passed on to outer try statements; if no handler is found, it is an **unhandled** exception and execution stops with a message as shown above.\n",
    "   \n",
    "   \n",
    "   Some examples of errors and their messages:\n",
    "   \n",
    "    - except IOError: print('An error occurred trying to read the file.')\n",
    "\n",
    "    - except ValueError: print('Non-numeric data found in the file.')\n",
    "\n",
    "    - except ImportError: print \"NO module found\"\n",
    "\n",
    "    - except EOFError: print('Why did you do an EOF on me?')\n",
    "\n",
    "    - except KeyboardInterrupt: print('You cancelled the operation.')\n",
    "\n",
    "    - except: print('An error occurred.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "ead84962",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter a numerator:20\n",
      "Enter a denominator:0\n",
      "Denominator cannot be zero. Please insert another number\n",
      "Program ends\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    numerator = int(input(\"Enter a numerator:\"))\n",
    "    denominator = int(input(\"Enter a denominator:\"))\n",
    "    \n",
    "    print(numerator/denominator)\n",
    "    \n",
    "except:\n",
    "    print(\"Denominator cannot be zero. Please insert another number\")\n",
    "    \n",
    "print(\"Program ends\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4377bfd2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "5c0a8e0c",
   "metadata": {},
   "source": [
    "**This piece of code will execute the except statement if any exception occurs even if it is not the Zero division Error. It is therefore possible to specify what exception you will be excpecting in your except statement**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "12f75cf9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "1d8ee278",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter a numerator:20\n",
      "Enter a denominator:j\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "invalid literal for int() with base 10: 'j'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[16], line 4\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m      3\u001b[0m     numerator \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mint\u001b[39m(\u001b[38;5;28minput\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mEnter a numerator:\u001b[39m\u001b[38;5;124m\"\u001b[39m))\n\u001b[1;32m----> 4\u001b[0m     denominator \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mint\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;28;43minput\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mEnter a denominator:\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m      6\u001b[0m     \u001b[38;5;28mprint\u001b[39m(numerator\u001b[38;5;241m/\u001b[39mdenominator)\n\u001b[0;32m      8\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mZeroDivisionError\u001b[39;00m:\n",
      "\u001b[1;31mValueError\u001b[0m: invalid literal for int() with base 10: 'j'"
     ]
    }
   ],
   "source": [
    "#This except block is only handling the Zero Division Error\n",
    "try:\n",
    "    numerator = int(input(\"Enter a numerator:\"))\n",
    "    denominator = int(input(\"Enter a denominator:\"))\n",
    "    \n",
    "    print(numerator/denominator)\n",
    "    \n",
    "except ZeroDivisionError:\n",
    "    print(\"Denominator cannot be zero. Please insert another number\")\n",
    "    \n",
    "print(\"Program ends\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "e0ce5cd4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter a numerator:20\n",
      "Enter a denominator:j\n",
      "Please input an integer value only\n",
      "Program ends\n"
     ]
    }
   ],
   "source": [
    "# To handle multiple exceptions you can have multiple except blocks\n",
    "try:\n",
    "    numerator = int(input(\"Enter a numerator:\"))\n",
    "    denominator = int(input(\"Enter a denominator:\"))\n",
    "    \n",
    "    print(numerator/denominator)\n",
    "    print(name)\n",
    "    \n",
    "except ZeroDivisionError:\n",
    "    print(\"Denominator cannot be zero. Please insert another number\")\n",
    "\n",
    "except ValueError:\n",
    "    print(\"Please input an integer value only\")\n",
    "\n",
    "except NameError:\n",
    "    print(\"Name is not defined\")\n",
    "    \n",
    "    \n",
    "print(\"Program ends\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0f6b0888",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ae8e109d",
   "metadata": {},
   "outputs": [],
   "source": [
    "numerator = int(input(\"Enter a numerator:\"))\n",
    "denominator = int(input(\"Enter a denominator:\"))\n",
    "\n",
    "if denominator == 0:\n",
    "    print(\"This will give you an error\")\n",
    "else:\n",
    "    print(numerator/denominator)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6eaf687a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4725132a",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "try:\n",
    "    numerator = int(input(\"Enter a numerator:\"))\n",
    "    denominator = int(input(\"Enter a denominator:\"))\n",
    "    \n",
    "    print(numerator/denominator)\n",
    "    print(name)\n",
    "    \n",
    "except (ZeroDivisionError, ValueError, NameError, IOError, TypeError):\n",
    "    print(\"There is an error\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4efee616",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "6b19a9a8",
   "metadata": {},
   "source": [
    "**A try block can also have a finally block/statement which is always executed after normal termination of try block or after try block terminates due to some exception.**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ad4541cc",
   "metadata": {},
   "outputs": [],
   "source": [
    "#The finally block always executes after normal termination of try block or after try block terminates due to some exception.\n",
    "\n",
    "def divide(x, y):\n",
    "    try:\n",
    "        result = x // y\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Sorry ! You are dividing by zero \")\n",
    "    else:\n",
    "        print(\"Yeah ! Your answer is :\", result)\n",
    "    finally: \n",
    "        print('This is always executed')  \n",
    " \n",
    "# Look at parameters and note the working of Program\n",
    "divide(3, 2)\n",
    "divide(3, 0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8d7d9ed2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1f6f2d44",
   "metadata": {},
   "outputs": [],
   "source": [
    "f = None\n",
    "try:\n",
    "    f = open(\"file.txt\", \"r\") # assuming that the file exists but the  read() is not working\n",
    "    content = f.read()\n",
    "    print(content)\n",
    "except IOError:\n",
    "    print(\"An IOError occurred.\")\n",
    "finally:\n",
    "    if f:\n",
    "        f.close() # this line closes the file, whether or not an error occurs.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "17f37685",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "71ad8834",
   "metadata": {},
   "source": [
    "In this example, the try block opens a file and reads its contents. If an IOError occurs, the except block will be executed and the error message will be printed. Regardless of whether an exception was raised or not, the code in the finally block will always be executed, closing the file."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5349200e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "raw",
   "id": "a2df72c8",
   "metadata": {},
   "source": [
    "try:\n",
    "    run first\n",
    "except:\n",
    "    if exception occurs\n",
    "finally:\n",
    "    regardless - just run"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aa44d3d2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "1323f002",
   "metadata": {},
   "source": [
    "### For reference, you can use these links to understand exception handling \n",
    "- https://www.geeksforgeeks.org/try-except-else-and-finally-in-python/\n",
    "- https://www.geeksforgeeks.org/errors-and-exceptions-in-python/\n",
    "- https://docs.python.org/3/library/exceptions.html\n",
    "- https://swcarpentry.github.io/python-novice-inflammation/09-errors/index.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "61ba64a6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d72d3363",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d53faee0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8b355141",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ad5b3156",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
